name: eelive
favicon: null
layout_spectrum: 0.27076
typography_spectrum: 0.14488
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1c1c'
    - '#ffffff'
    - '#e51954'
    - '#36e9d3'
    - '#247066'
  brandStrength: 0.125
  lightness: 0.375
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
